substitutions:
  name: apc-ups
  device_description: "Monitor and control a APC UPS via RS232"
  external_components_source: github://syssi/esphome-apc-ups@main
  tx_pin: GPIO16
  rx_pin: GPIO17

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-apc-ups"
    version: 1.0.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
logger:

# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
api:

# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

uart:
  - id: uart_0
    baud_rate: 2400
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
    debug:
      direction: BOTH
      dummy_receiver: false
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);

apc_ups:
  - id: ups0
    uart_id: uart_0

binary_sensor:
  - platform: apc_ups
    apc_ups_id: ups0
    runtime_calibration:
      name: "${name} runtime calibration"
    smart_trim:
      name: "${name} smart trim"
    smart_boost:
      name: "${name} smart boost"
    on_line:
      name: "${name} on line"
    on_battery:
      name: "${name} on battery"
    output_overloaded:
      name: "${name} output overloaded"
    battery_low:
      name: "${name} battery low"
    replace_battery:
      name: "${name} replace battery"

sensor:
  - platform: apc_ups
    apc_ups_id: ups0
    battery_voltage:
      name: "${name} battery voltage"
    grid_frequency:
      name: "${name} grid frequency"
    grid_voltage:
      name: "${name} grid voltage"
    ac_output_voltage:
      name: "${name} ac output voltage"
    ac_output_load:
      name: "${name} ac output load"
    status_bitmask:
      name: "${name} status bitmask"
    state_of_charge:
      name: "${name} state of charge"
    estimated_runtime:
      name: "${name} estimated runtime"

text_sensor:
  - platform: apc_ups
    apc_ups_id: ups0
    cause_of_last_transfer:
      name: "${name} cause of last transfer"
